package forms;

import module_3.Class.*;
import javax.swing.*;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.Date;
import java.time.LocalDate;
import java.util.List;

public class frmLibroComprasIVA extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmLibroComprasIVA.class.getName());

    private static final BigDecimal UNO_MAS_IVA = new BigDecimal("1.13");

    private int idEmpresaActual = 1; // Vendrá de la sesión cuando exista FrmLogin
    private OrdenCompra ordenSeleccionada = null;

    /**
     * Creates new form frmLibroComprasIVA
     */
    public frmLibroComprasIVA() {
        initComponents();
        cargarFecha();
        cargarOrdenesElegibles();
    }

    private void cargarFecha() {
        txtFecha.setText(LocalDate.now().toString());
    }

    private void cargarOrdenesElegibles() {
        LibroComprasIVADAO dao = new LibroComprasIVADAO();
        List<OrdenCompra> elegibles = dao.listarOrdenesElegibles(idEmpresaActual);
        cmbOrdenCompra.removeAllItems();
        for (OrdenCompra o : elegibles) {
            cmbOrdenCompra.addItem(o);
        }
        if (cmbOrdenCompra.getItemCount() == 0) {
            JOptionPane.showMessageDialog(this,
                    "No hay órdenes recibidas pendientes de registrar en el libro de IVA.");
        }
    }

    private void cmbOrdenCompraActionPerformed(java.awt.event.ActionEvent evt) {
        ordenSeleccionada = (OrdenCompra) cmbOrdenCompra.getSelectedItem();
        if (ordenSeleccionada == null) {
            limpiarCamposAutollenados();
            return;
        }

        // Proveedor: necesitas el nombre, no solo el id.
        // Si OrdenCompra no trae el nombre del proveedor, lo buscamos aparte.
// Proveedor: usamos obtenerPorId, que devuelve el objeto Proveedor completo
        ProveedorDAO proveedorDAO = new ProveedorDAO();
        Proveedor proveedor = proveedorDAO.obtenerPorId(ordenSeleccionada.getIdProveedor(), idEmpresaActual);
        txtProveedor.setText(proveedor != null ? proveedor.getNombre() : "(Proveedor #" + ordenSeleccionada.getIdProveedor() + ")");
        BigDecimal total = ordenSeleccionada.getTotal();
        BigDecimal montoGravado = total.divide(UNO_MAS_IVA, 2, RoundingMode.HALF_UP);
        BigDecimal iva = total.subtract(montoGravado);

        txtMontoGrabado.setText(montoGravado.toString());
        txtIVA.setText(iva.toString());
        txtTotal.setText(total.toString());
    }

    private void limpiarCamposAutollenados() {
        txtProveedor.setText("");
        txtMontoGrabado.setText("");
        txtIVA.setText("");
        txtTotal.setText("");
    }

    private void limpiarFormulario() {
        txtNumeroDocumento.setText("");
        limpiarCamposAutollenados();
        ordenSeleccionada = null;
    }

    private BigDecimal calcularMontoGravado(BigDecimal total) {
        return total.divide(UNO_MAS_IVA, 2, java.math.RoundingMode.HALF_UP);
    }

    private BigDecimal calcularIva(BigDecimal total, BigDecimal montoGravado) {
        return total.subtract(montoGravado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbOrdenCompra = new javax.swing.JComboBox<>();
        lblSelectorCompra = new javax.swing.JLabel();
        lblProveedor = new javax.swing.JLabel();
        txtProveedor = new javax.swing.JTextField();
        lblMontoGrabado = new javax.swing.JLabel();
        txtMontoGrabado = new javax.swing.JTextField();
        lblIVA = new javax.swing.JLabel();
        txtIVA = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        lblNumeroDocumento = new javax.swing.JLabel();
        txtNumeroDocumento = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblSelectorCompra.setText("Selector de compra");

        lblProveedor.setText("Proveedor");

        lblMontoGrabado.setText("Monto grabado");

        lblIVA.setText("IVA");

        lblTotal.setText("Total");

        lblNumeroDocumento.setText("Numero de documento");

        lblFecha.setText("Fecha");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSelectorCompra)
                            .addComponent(lblProveedor)
                            .addComponent(lblMontoGrabado)
                            .addComponent(lblIVA)
                            .addComponent(lblTotal)
                            .addComponent(lblNumeroDocumento)
                            .addComponent(lblFecha))
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbOrdenCompra, 0, 267, Short.MAX_VALUE)
                            .addComponent(txtProveedor)
                            .addComponent(txtMontoGrabado)
                            .addComponent(txtIVA)
                            .addComponent(txtTotal)
                            .addComponent(txtNumeroDocumento)
                            .addComponent(txtFecha)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(btnGuardar)))
                .addContainerGap(316, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbOrdenCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSelectorCompra))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProveedor)
                    .addComponent(txtProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMontoGrabado)
                    .addComponent(txtMontoGrabado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIVA)
                    .addComponent(txtIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroDocumento)
                    .addComponent(txtNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFecha)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(btnGuardar)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        if (ordenSeleccionada == null) {
            JOptionPane.showMessageDialog(this, "Selecciona una orden de compra.");
            return;
        }

        String numeroDoc = txtNumeroDocumento.getText().trim();
        if (numeroDoc.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingresa el número de documento (factura).");
            return;
        }

        LibroComprasIVADAO dao = new LibroComprasIVADAO();

        // Validar que no exista ya esa factura para ese proveedor
        if (dao.existeFactura(idEmpresaActual, ordenSeleccionada.getIdProveedor(), numeroDoc)) {
            JOptionPane.showMessageDialog(this,
                    "Ya existe un registro con ese número de documento para este proveedor.");
            return;
        }

        BigDecimal total = ordenSeleccionada.getTotal();
        BigDecimal montoGravado = total.divide(UNO_MAS_IVA, 2, RoundingMode.HALF_UP);
        BigDecimal iva = total.subtract(montoGravado);

        LibroComprasIVA registro = new LibroComprasIVA(
                idEmpresaActual,
                ordenSeleccionada.getIdOrden(),
                ordenSeleccionada.getIdProveedor(),
                numeroDoc,
                Date.valueOf(LocalDate.now()),
                montoGravado,
                iva,
                total
        );

        boolean exito = dao.insertar(registro);

        if (exito) {
            JOptionPane.showMessageDialog(this, "Registro guardado en el libro de compras IVA.");
            limpiarFormulario();
            cargarOrdenesElegibles(); // refresca: esa orden ya no debe volver a aparecer
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar. Intenta de nuevo.");
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmLibroComprasIVA().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<OrdenCompra> cmbOrdenCompra;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblIVA;
    private javax.swing.JLabel lblMontoGrabado;
    private javax.swing.JLabel lblNumeroDocumento;
    private javax.swing.JLabel lblProveedor;
    private javax.swing.JLabel lblSelectorCompra;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtIVA;
    private javax.swing.JTextField txtMontoGrabado;
    private javax.swing.JTextField txtNumeroDocumento;
    private javax.swing.JTextField txtProveedor;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
