package forms;

import module_3.Class.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.math.BigDecimal;
import java.sql.Date;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

public class frmRequisicion extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmRequisicion.class.getName());

    private DefaultTableModel modeloTabla;
    private List<DetalleRequisicion> listaDetalle = new ArrayList<>();
    private int idEmpresaActual = 1; // Esto después vendrá de la sesión
    private frmLobby padre;

    public frmRequisicion(frmLobby padre) {

        initComponents();
        inicializarTabla();
        cargarFecha();
        cargarProductos();
        this.padre = padre;
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                padre.setVisible(true);
            }
        });
    }

    private void inicializarTabla() {
        modeloTabla = new DefaultTableModel(
                new String[]{"#", "Producto", "Cantidad", "Observación"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Tabla solo lectura
            }
        };
        tblDetalle.setModel(modeloTabla);
    }

    // ─────────────────────────────────────────
    // CARGAR FECHA DE HOY
    // ─────────────────────────────────────────
    private void cargarFecha() {
        txtFecha.setText(LocalDate.now().toString());
    }

    // ─────────────────────────────────────────
    // CARGAR PRODUCTOS EN EL COMBO
    // ─────────────────────────────────────────
    private void cargarProductos() {
        ProductoDAO dao = new ProductoDAO();
        List<Producto> todos = dao.listar();
        cmbSelectorProducto.removeAllItems();
        for (Producto p : todos) {
            cmbSelectorProducto.addItem(p);
        }
    }

    private void limpiarFormulario() {
        txtObservacionCabecera.setText("");
        txtCantidad.setText("");
        txtObservacionLinea.setText("");
        modeloTabla.setRowCount(0);
        listaDetalle.clear();
        cmbSelectorProducto.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFecha = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        lblObservacionCabecera = new javax.swing.JLabel();
        txtObservacionCabecera = new javax.swing.JTextField();
        lblSelectorProducto = new javax.swing.JLabel();
        cmbSelectorProducto = new javax.swing.JComboBox<>();
        lblCantidad = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtObservacionLinea = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetalle = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblFecha.setText("Fecha");

        txtFecha.setEditable(false);

        lblObservacionCabecera.setText("Observación cabecera");

        lblSelectorProducto.setText("Selector de producto");

        lblCantidad.setText("Cantidad");

        jLabel1.setText("Observacion de la linea");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        tblDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblDetalle);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnQuitar.setText("Quitar/Eliminar");
        btnQuitar.addActionListener(this::btnQuitarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFecha)
                                .addGap(51, 51, 51)
                                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblObservacionCabecera)
                                    .addComponent(lblSelectorProducto)
                                    .addComponent(lblCantidad)
                                    .addComponent(jLabel1))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtObservacionCabecera)
                                    .addComponent(cmbSelectorProducto, 0, 220, Short.MAX_VALUE)
                                    .addComponent(txtCantidad)
                                    .addComponent(txtObservacionLinea))
                                .addGap(123, 123, 123)
                                .addComponent(btnAgregar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(btnGuardar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(btnQuitar)))))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFecha)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblObservacionCabecera)
                    .addComponent(txtObservacionCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSelectorProducto)
                            .addComponent(cmbSelectorProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnAgregar)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidad)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtObservacionLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(btnGuardar)
                        .addGap(29, 29, 29)
                        .addComponent(btnQuitar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed

        int filaSeleccionada = tblDetalle.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una línea para quitar.");
            return;
        }
        modeloTabla.removeRow(filaSeleccionada);
        listaDetalle.remove(filaSeleccionada);


    }//GEN-LAST:event_btnQuitarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        if (listaDetalle.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Agrega al menos un producto antes de guardar.");
            return;
        }

        String obsGeneral = txtObservacionCabecera.getText().trim();

        Requisicion req = new Requisicion(
                idEmpresaActual,
                Date.valueOf(LocalDate.now()),
                "PENDIENTE",
                obsGeneral.isEmpty() ? null : obsGeneral
        );

        RequisicionDAO dao = new RequisicionDAO();
        boolean exito = dao.insertarRequisicionCompleta(req, listaDetalle);

        if (exito) {
            JOptionPane.showMessageDialog(this, "Requisición guardada correctamente.");
            limpiarFormulario();
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar la requisición. Intenta de nuevo.");
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
       
        Producto productoSeleccionado = (Producto) cmbSelectorProducto.getSelectedItem();
        String cantidadTexto = txtCantidad.getText().trim();
        String obsLinea = txtObservacionLinea.getText().trim();

        // Validaciones
        if (productoSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Selecciona un producto.");
            return;
        }
        if (cantidadTexto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingresa una cantidad.");
            return;
        }

        BigDecimal cantidad;
        try {
            cantidad = new BigDecimal(cantidadTexto);
            if (cantidad.compareTo(BigDecimal.ZERO) <= 0) {
                JOptionPane.showMessageDialog(this, "La cantidad debe ser mayor a cero.");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "La cantidad debe ser un número válido.");
            return;
        }

        // Agregar a la lista en memoria
        DetalleRequisicion detalle = new DetalleRequisicion(
                0, // idRequisicion, se asigna al guardar
                productoSeleccionado.getIdProducto(),
                cantidad,
                obsLinea.isEmpty() ? null : obsLinea
        );
        listaDetalle.add(detalle);

        // Agregar fila a la tabla visual
        modeloTabla.addRow(new Object[]{
            modeloTabla.getRowCount() + 1,
            productoSeleccionado.getNombre(),
            cantidad,
            obsLinea
        });

        // Limpiar campos
        txtCantidad.setText("");
        txtObservacionLinea.setText("");
        cmbSelectorProducto.setSelectedIndex(0);
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JComboBox<Producto> cmbSelectorProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblObservacionCabecera;
    private javax.swing.JLabel lblSelectorProducto;
    private javax.swing.JTable tblDetalle;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtObservacionCabecera;
    private javax.swing.JTextField txtObservacionLinea;
    // End of variables declaration//GEN-END:variables
}
